### ISSUE TITLE
Doesn't work in MacOS terminal

### ISSUE THREAD

**Issue by ChopsKingsland** [feluxe/sty#29]
I have got this working in the terminal in VSCode, but it doesn't work in the built-in MacOS terminal app... How do I get this working?

**Comment by feluxe** [comment]
It should be working (except for RGB-colors). Which OS version do you use? What do you get from `echo $TERM` ?

**Comment by ChopsKingsland** [comment]
I have tried with both RGB and built in colours and it still doesn't work... when I run `echo $TERM`, it gives the output `xterm-256color`

**Comment by feluxe** [comment]
Thanks for the info. What do you get when you open a Python REPL in your Terminal and run `print("\x1b[31m" + "text" + "\x1b[39m")`? And what do you get when you run `print(sty.fg.red + "text" + sty.fg.rs)`?

**Comment by ChopsKingsland** [comment]
<img width="309" alt="image" src="https://user-images.githubusercontent.com/18499854/106383491-448d9e80-63be-11eb-83e0-c7446794e0b9.png">

<img width="312" alt="image" src="https://user-images.githubusercontent.com/18499854/106383492-4a837f80-63be-11eb-89e2-fff76caa63cc.png">

**Comment by feluxe** [comment]
Both results look red to me. I don't see what's wrong here?

**Comment by ChopsKingsland** [comment]
I don't understand what is wrong either, because this is what I see in VSCode terminal: 
![image](https://user-images.githubusercontent.com/18499854/106391813-0e184980-63e7-11eb-9380-73b42d0ca002.png)

And this is what I see in MacOS native terminal: 
![image](https://user-images.githubusercontent.com/18499854/106391832-21c3b000-63e7-11eb-8485-a31f7c5458c1.png)

**Comment by feluxe** [comment]
Do you see any colors if you clone the sty repo and run the tests:

```bash
git clone git@github.com:feluxe/sty.git
cd sty
python -m tests
```
?

**Comment by ChopsKingsland** [comment]
yep, I see colours

**Comment by feluxe** [comment]
What happens if you print this line from within your script?

```python
print("\x1b[31m" + "text" + "\x1b[39m")
```

**Comment by ChopsKingsland** [comment]
![image](https://user-images.githubusercontent.com/18499854/106607083-ce726e80-655a-11eb-9676-ddb9c8143730.png)
that works

**Comment by feluxe** [comment]
And if you do the same thing but replace `print("\x1b[31m" + "text" + "\x1b[39m")` with  `print(sty.fg.red + "text" + sty.fg.rs)`?

**Comment by feluxe** [comment]
I'm sorry, but I don't think the issue is on sty's side here, since the tests pass on your terminal.
I would need more information in order to figure out what's going on in your specific situation.
I'm closing this for now.
